name: CI/CD

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Give execute permission to mvnw script
      run: chmod +x ./api/mvnw
    
    - name: Test Spring Boot application
      run: ./api/mvnw clean test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Give execute permission to mvnw script
      run: chmod +x ./api/mvnw
    
    - name: Package Spring Boot application
      run: ./api/mvnw clean package
