name: CI/CD

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: All the Tests and Coverage check
        run: mvn -f /home/runner/work/gestion-des-boutiques/gestion-des-boutiques/api/pom.xml clean install -Dspring.profiles.active=test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: Package Spring Boot application
        run: mvn -f /home/runner/work/gestion-des-boutiques/gestion-des-boutiques/api/pom.xml clean package -Dspring.profiles.active=test
